apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
spec:
  containers:
  - name: {{ .Release.Name }}
    image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    command: {{ .Values.command }}
    
