# Default values for debug-pod.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: alpine
  tag: latest
  pullPolicy: IfNotPresent

command: ["sh", "-c", "trap 'echo Bye' SIGTERM SIGINT; sleep infinity & wait"]